### ISSUE TITLE
No chance to click on image link

### ISSUE THREAD

**Issue by Libig** [GianlucaGuarini/jQuery.BlackAndWhite#57]
Hi,
At first, thanks for this usefull plugin!

Since version 0.3.4 I am having problems with disappeared links. When hoovering cursor doesn't change to hand neither there is any advice that image is placed within a href tag.

My html is common:

                    <div class="quicklinks-wrapper">                        
                        <ul>
                                <li class="bwWrapper"><a href="/link1"><img src="/files/ouorw0wl63.nrjo3rwpnk.quick-link-1r.png" title="link1" alt="link1" class=""></a>
                                </li>
                                <li class="bwWrapper"><a href="/link2"><img src="/files/0xubeb5ukr.quick-link-2.png" title="link2" alt="link2" class=""></a>
                                </li>
                                <li class="bwWrapper"><a href="/link3"><img src="/files/pphxprmy1r.quick-link-3.png" title="link3" alt="link3" class=""></a>
                                </li>
                        </ul>
                    </div>

Switching back to ver. 0.2.8 all links are again active work.

The only difference I see in generated code is attribute crossorigin="anonymous" added to img tag in new versions of BlackAndWhite.

Thanks!

**Comment by GianlucaGuarini** [comment]
Move the class `bwWrapper` from the `li` to the `a` and it should work

**Comment by Libig** [comment]
Thanks. However it is more comfortable to mark wrapper with the class in order to have all links inside with this behaviour.
