### ISSUE TITLE
Firefox 35.0 update prevents filters

### ISSUE THREAD

**Issue by woro83c** [GianlucaGuarini/jQuery.BlackAndWhite#58]
Hi

Just noticed when updating to the latest firefox that the black and white filter wont work. Reading the firefox release notes they have enabled filters by default but cant see exactly whats causing it.

Cheers!

**Comment by GianlucaGuarini** [comment]
are you using the latest version of jQuery.BlackAndWhite?

**Comment by GianlucaGuarini** [comment]
This issue got fixed with the new release
