### ISSUE TITLE
Only displaying color version

### ISSUE THREAD

**Issue by iggmack** [GianlucaGuarini/jQuery.BlackAndWhite#65]
Hello, I have some issues with the plugin. The BW wrapper image only displays the filename. In Firefox none of the images is displaying

See what I mean here: http://www.selanderax.se/projekt/

**Comment by GianlucaGuarini** [comment]
Please change `$('img').BlackAndWhite` with `$('.bwWrapper').BlackAndWhite`

**Comment by iggmack** [comment]
yes it's $('.bwWrapper').BlackAndWhite

**Comment by GianlucaGuarini** [comment]
Remove the class be wrapper from your I'm tags

**Comment by iggmack** [comment]
Thanks for a quick reply. 

The only class on the img's is "wp-post-image" other than the generated "BWFilter" and "BWfade"

**Comment by GianlucaGuarini** [comment]
Yeah I see it seems the error is somewhere else..now I have no time to investigate where is the problem

**Comment by iggmack** [comment]
I get this error:

"Image from origin 'http://selanderax.se' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.selanderax.se' is therefore not allowed access."

Any ideas?

**Comment by GianlucaGuarini** [comment]
Try using relative urls to load your images

**Comment by iggmack** [comment]
Yes that worked! Thank you

**Comment by GianlucaGuarini** [comment]
Awesome I will close this issue
