### ISSUE TITLE
TypeError: $.browser is undefined

### ISSUE THREAD

**Issue by vinylroads** [GianlucaGuarini/jQuery.BlackAndWhite#66]
Hello,

I use your plugin on a website I’ve made this is several years. It works very well. Thanks !

I’m working on this website to update the template and i see that your plugin is no more compatible with jquery 1.11.3

On your demo, you use jQuery 1.8.1

If i use jquery 1.11, i have this error in console :

TypeError: $.browser is undefined

I think the .browser call has been removed in jquery 1.9 

Could you update the plugin ?

Thank you.

**Comment by GianlucaGuarini** [comment]
`$.browser` is nowhere in my code

**Comment by vinylroads** [comment]
Ok, but if i load query 1.11, i have this error in console :+1: 
```
TypeError: undefined is not an object (evaluating '$.browser.msie')
BlackAndWhitejQuery.BlackAndWhite.js:60
(fonction anonyme)zzz-test-bw.html:14
dispatchjquery.js:3703
handlejquery.js:3703
```
I've tested it on a simple html page without any script except  jQuery and jQuery.BlackAndWhite

**Comment by GianlucaGuarini** [comment]
can you make a jsfiddle please?

**Comment by vinylroads** [comment]
yep, give me 5 minutes ;-)

**Comment by vinylroads** [comment]
Here is a fiddle with jQuery 1.11 :

https://jsfiddle.net/Vinyl/17p9hn7L/2/embedded/result/

Here is a fiddle with  jQuery 1.8.1 :

**Comment by vinylroads** [comment]
I don't know why but it doesn't work also on jsfiddle with jQuery 1.8 :+1: https://jsfiddle.net/Vinyl/wbjdge6r/embedded/result/

But it works on my demo page. I'll share a link.

**Comment by vinylroads** [comment]
Here is a demo with jQuery 1.8 :
http://jquery-blackandwhite.reflexion-graphic.com/zzz-test-bw.html

jQuery 1.11 :
http://jquery-blackandwhite.reflexion-graphic.com/zzz-test-bw-2.html

I think it is not working on jsfiddle because i'm loading the image from an external source, not sure about this.

**Comment by vinylroads** [comment]
I've updated the 2 demo pages. It was messed up because css was not loaded. Now it's ok. You can see the issue ?

**Comment by GianlucaGuarini** [comment]
well you are using the `0.2.3` to fix the issue you can start by using the latest ` 0.3.7`

**Comment by vinylroads** [comment]
yes, i've done that before and sorry for the wrong version. I update my demo page now.

**Comment by vinylroads** [comment]
It's now updated to 0.3.6

**Comment by GianlucaGuarini** [comment]
and it's working..

**Comment by vinylroads** [comment]
Ho, i'm really sorry to have disturb you.I see that i may have messed up in my code. I was loading the last version but i was also loading the wrong version. I feel awkward...

**Comment by GianlucaGuarini** [comment]
no prob
